version: 0.2

run-as: ubuntu

env:
  shell: bash
  variables:
    DEPLOYMENT_NAME: roman
    ENVIRONMENT: sandbox
    USE_FLOATING: 0
    IMAGE_TAG: latest
    COMMON_TAG: common-latest
    ACCOUNT_ID: xxxxxx
    ADMIN_ROLE: yyyyyyyyyyy

#   secrets-manager:
#     key: secret-id:json-key:version-stage:version-id
#   git-credential-helper: no | yes

# proxy:
#   upload-artifacts: no | yes
#   logs: no | yes

# batch:
#   fast-fail: false | true
#   # build-list:
#   # build-matrix:
#   # build-graph:

phases:
  install:
    run-as: ubuntu
    runtime-versions:
      runtime: aws/codebuild/standard:5.0
    commands:
      - echo ---------------------------------------------------------------
      - echo Installing node...
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
      - bash ~/.nvm/nvm.sh
      - source ~/.bashrc
      - nvm install node
      - npm config set registry http://registry.npmjs.org/
      - echo ---------------------------------------------------------------
      - echo Installing miniconda...
      - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
      - chmod +x Miniconda3-latest-Linux-x86_64.sh
      - ./Miniconda3-latest-Linux-x86_64.sh -b -p ~/python
      - /home/ec2-user/python/bin/conda   init
      - source /home/ec2-user/.bashrc
      - echo ---------------------------------------------------------------
      - echo Installing pip requirements...
      - pip install -r requirements.txt
  build:
    run-as: ubuntu
    commands:
      - echo ---------------------------------------------------------------
      - echo Sourcing environment files...
      - source stable-env
      - source derived-env
      - echo ---------------------------------------------------------------
      - image-build
  post_build:
    run-as: ubuntu
    commands:
      - echo ---------------------------------------------------------------
      - echo Sourcing environment files...
      - source stable-env
      - source derived-env
      - echo ---------------------------------------------------------------
      - image-test
      - image-push
      - image-scan
