#!/bin/bash

# ------------------------------------------------------------------------------------
#
# This file is used to initialize aspects of JupyterHub which are common to both
# cloud and standalone usage.  post start actions which are unique to the cloud
# should be placed either in the config YAML or in another file so that they
# don't break the standalone/CI use case.   Only this file should be called from
# both the Dockerfile and the hub post start hook.
#
# This file implements:
#
# 1. Setup and update of the default-home-contents
#
# 2. Notebook setup for class and test notebooks.
#
# It should not implement e.g. CRDS symlink setup which is tied to EFS/cloud
# and won't work standalone.
#
# It's a good idea to keep this relatively light weight / short running.
#
set -eu

rsync -r  /etc/default-home-contents/ /home/jovyan

# .............................................................................................

/opt/common-scripts/git-sync   https://github.com/spacetelescope/notebooks.git   master   /home/jovyan/spacetelescope-notebooks

/opt/common-scripts/git-sync  https://github.com/spacetelescope/tike_content  master  /home/jovyan/tike_content

# .............................................................................................

mkdir -p /opt/environments/tess/tests

echo <<EOF >/opt/environments/tess/tests/notebooks
    /home/jovyan/tike_content/code/test-cloud-lightkurve.py
    #/home/jovyan/tike_content/code/test_notebooks/packages_priority1.ipynb
    /home/jovyan/tike_content/code/test_notebooks/packages_priority2.ipynb
    /home/jovyan/tike_content/code/test_notebooks/packages_priority3.ipynb
EOF

/opt/common-scripts/set-notebook-kernel tess 'TESS' `cat /opt/environments/tess/tests/notebooks`

# .............................................................................................

echo <<EOF >/opt/environments/tess/tests/long-notebooks
    /home/jovyan/spacetelescope-notebooks/notebooks/MAST/TESS/beginner_how_to_use_lc/beginner_how_to_use_lc.ipynb
    /home/jovyan/spacetelescope-notebooks/notebooks/MAST/TESS/beginner_how_to_use_dvt/beginner_how_to_use_dvt.ipynb
    /home/jovyan/spacetelescope-notebooks/notebooks/MAST/TESS/beginner_tour_lc_tp/beginner_tour_lc_tp.ipynb
    /home/jovyan/spacetelescope-notebooks/notebooks/MAST/TESS/tess_removing_scattered_light_using_regression/tess_removing_scattered_light_using_regression.ipynb
    /home/jovyan/spacetelescope-notebooks/notebooks/MAST/TESS/beginner_tess_exomast/beginner_tess_exomast.ipynb
    /home/jovyan/spacetelescope-notebooks/notebooks/MAST/TESS/beginner_tic_search_hd209458/beginner_tic_search_hd209458.ipynb
    /home/jovyan/spacetelescope-notebooks/notebooks/MAST/TESS/interm_gi_query/interm_gi_query.ipynb
    /home/jovyan/spacetelescope-notebooks/notebooks/MAST/TESS/beginner_astroquery_dv/beginner_astroquery_dv.ipynb
    /home/jovyan/spacetelescope-notebooks/notebooks/MAST/TESS/beginner_how_to_use_ffi/beginner_how_to_use_ffi.ipynb
    /home/jovyan/spacetelescope-notebooks/notebooks/MAST/TESS/beginner_how_to_use_tp/beginner_how_to_use_tp.ipynb

    /home/jovyan/spacetelescope-notebooks/MAST/Kepler/Kepler_Lightcurve/kepler_lightcurve.ipynb
    /home/jovyan/spacetelescope-notebooks/MAST/Kepler/Kepler_TPF/kepler_tpf.ipynb
    /home/jovyan/spacetelescope-notebooks/MAST/Kepler/Kepler_DVT/Kepler_DVT.ipynb
    /home/jovyan/spacetelescope-notebooks/MAST/Kepler/Kepler_FFI/kepler_ffi.ipynb
    /home/jovyan/spacetelescope-notebooks/MAST/K2/K2_Lightcurve/K2_Lightcurve.ipynb
    /home/jovyan/spacetelescope-notebooks/MAST/K2/K2_TPF/K2_TPF.ipynb
    /home/jovyan/spacetelescope-notebooks/MAST/K2/beginner_how_to_use_ffi/beginner_how_to_use_ffi.ipynb

    /home/jovyan/spacetelescope-notebooks/MAST/Kepler/kepler_using_light_curve_products_with_lightkurve/kepler_using_light_curve_products_with_lightkurve.ipynb
    /home/jovyan/spacetelescope-notebooks/MAST/Kepler/kepler_using_target_pixel_file_products_with_lightkurve/kepler_using_target_pixel_file_products_with_lightkurve.ipynb
    /home/jovyan/spacetelescope-notebooks/MAST/Kepler/kepler_plotting_target_pixel_files/kepler_plotting_target_pixel_files.ipynb
    /home/jovyan/spacetelescope-notebooks/MAST/Kepler/kepler_searching_for_data_products/kepler_searching_for_data_products.ipynb
    /home/jovyan/spacetelescope-notebooks/MAST/Kepler/kepler_creating_your_own_light_curves/kepler_creating_your_own_light_curves.ipynb
    /home/jovyan/spacetelescope-notebooks/MAST/Kepler/kepler_combining_multiple_quarters/kepler_combining_multiple_quarters.ipynb
    /home/jovyan/spacetelescope-notebooks/MAST/Kepler/kepler_interactively_inspecting_target_pixel_files_and_light_curves/kepler_interactively_inspecting_target_pixel_files_and_light_curves.ipynb

    /home/jovyan/spacetelescope-notebooks/MAST/Kepler/kepler_instrumental_noise_1_data_gaps_and_quality_flags/kepler_instrumental_noise_1_data_gaps_and_quality_flags.ipynb
    /home/jovyan/spacetelescope-notebooks/MAST/Kepler/kepler_instrumental_noise_2_spurious_signals_and_time_sampling_effects/kepler_instrumental_noise_2_spurious_signals_and_time_sampling_effects.ipynb
    /home/jovyan/spacetelescope-notebooks/MAST/Kepler/kepler_instrumental_noise_3_seasonal_and_detector_effects/kepler_instrumental_noise_3_seasonal_and_detector_effects.ipynb
    /home/jovyan/spacetelescope-notebooks/MAST/Kepler/kepler_instrumental_noise_4_electronic_noise/kepler_instrumental_noise_4_electronic_noise.ipynb
    /home/jovyan/spacetelescope-notebooks/MAST/K2/k2_removing_instrumental_noise_using_pld/k2_removing_instrumental_noise_using_pld.ipynb

    /home/jovyan/spacetelescope-notebooks/MAST/Kepler/kepler_identifying_transiting_planet_signals/kepler_identifying_transiting_planet_signals.ipynb
    /home/jovyan/spacetelescope-notebooks/MAST/Kepler/kepler_measuring_a_rotation_period/kepler_measuring_a_rotation_period.ipynb
    /home/jovyan/spacetelescope-notebooks/MAST/Kepler/kepler_visualizing_periodic_signals_using_a_river_plot/kepler_visualizing_periodic_signals_using_a_river_plot.ipynb
    /home/jovyan/spacetelescope-notebooks/MAST/Kepler/kepler_verifying_the_location_of_a_signal/kepler_verifying_the_location_of_a_signal.ipynb
    /home/jovyan/spacetelescope-notebooks/MAST/Kepler/kepler_instrumental_noise_1_data_gaps_and_quality_flags/kepler_instrumental_noise_1_data_gaps_and_quality_flags.ipynb

    /home/jovyan/spacetelescope-notebooks/MAST/Kepler/kepler_instrumental_noise_2_spurious_signals_and_time_sampling_effects/kepler_instrumental_noise_2_spurious_signals_and_time_sampling_effects.ipynb
/home/jovyan/spacetelescope-notebooks/MAST/Kepler/kepler_instrumental_noise_3_seasonal_and_detector_effects/kepler_instrumental_noise_3_seasonal_and_detector_effects.ipynb
    /home/jovyan/spacetelescope-notebooks/MAST/Kepler/kepler_instrumental_noise_4_electronic_noise/kepler_instrumental_noise_4_electronic_noise.ipynb
    /home/jovyan/spacetelescope-notebooks/MAST/K2/k2_removing_instrumental_noise_using_pld/k2_removing_instrumental_noise_using_pld.ipynb

    /home/jovyan/spacetelescope-notebooks/MAST/Kepler/kepler_creating_periodograms/kepler_creating_periodograms.ipynb
    /home/jovyan/spacetelescope-notebooks/MAST/Kepler/kepler_how_to_understand_and_manipulate_the_periodogram_of_an_oscillating_star/kepler_how_to_understand_and_manipulate_the_periodogram_of_an_oscillating_star.ipynb
    /home/jovyan/spacetelescope-notebooks/MAST/Kepler/kepler_how_to_estimate_a_stars_mass_and_radius_using_asteroseismology/kepler_how_to_estimate_a_stars_mass_and_radius_using_asteroseismology.ipynb

    #/home/jovyan/spacetelescope-notebooks/notebooks/MAST/TESS/interm_tasc_lc/interm_tasc_lc.ipynb
    #/home/jovyan/spacetelescope-notebooks/notebooks/MAST/TESS/interm_tesscut_dss_overlay/interm_tesscut_dss_overlay.ipynb
    #/home/jovyan/spacetelescope-notebooks/notebooks/MAST/TESS/interm_tesscut_astroquery/interm_tesscut_astroquery.ipynb
    #/home/jovyan/spacetelescope-notebooks/notebooks/MAST/TESS/interm_tess_prf_retrieve/interm_tess_prf_retrieve.ipynb
    #/home/jovyan/spacetelescope-notebooks/notebooks/MAST/TESS/beginner_tess_tap_search/beginner_tess_tap_search.ipynb
    #/home/jovyan/spacetelescope-notebooks/notebooks/MAST/TESS/interm_tesscut_requests/interm_tesscut_requests.ipynb

EOF

/opt/common-scripts/set-notebook-kernel tess 'TESS' `cat /opt/environments/tess/tests/long-notebooks`
