#! /bin/bash

set -eu

# Run basic CI import and notebook tests.
time /opt/environments/test  # test all environments,  currently just tess

# Run long notebook tests
time /opt/common-scripts/test-notebooks tess `cat /opt/environments/tess/tests/long-notebooks`
