#! /usr/bin/env python
# -*-python-*-

"""Import the packages listed on the command line to test installation."""

import sys


def write_err(*args, **keys):
    print(*args, **keys, file=sys.stderr)
    sys.stderr.flush()
    

if (len(sys.argv) < 2):
    sys.exit(1)

import_list = sys.argv[1:]

errs = 0
for pkg in import_list:
    if pkg.startswith("#"):
        write_err("Skipping", pkg)
        continue
    write_err("Importing", pkg, "...", end="")
    try:
        exec(f"import {pkg}")
        write_err("ok")
    except ImportError:
        write_err("FAIL")
        errs += 1

sys.exit(errs)
