#! /bin/bash -eu

# Run a bash shell in the last tagged mission container.  This will lag
# behind any partially built container with newer image layers.

export IMAGE_RUN_PARS="$IMAGE_RUN_PARS -p 8888:8888 -it"

image-exec /bin/bash --rcfile /etc/bash.bashrc
