#! /bin/bash

# This script reduces image size by replacing redundant files in the image
# with a hard link to a master copy,  nominally anything under /opt/conda.
# The hard linked image is exported and re-imported in order to squash the
# file system.

set -eu

IMG=${1:-${IMAGE_ID}}
EXPORT_FILE=${2:-${IMG}.export}

# --------------------------------------------------------------------------
# First run the crosslink tool to eliminate redundant files using hard links

echo "----------------------------------------------------------------------"
echo "Crosslinking..."
time squash-crosslink ${IMG}

# ==========================================================================

# If it was mature,  a docker squash command could replace this...

# --------------------------------------------------------------------------
# Export the net file system to eliminate intermediate layers and redundancy

echo "----------------------------------------------------------------------"
echo "Exporting crosslinked file system..."
time squash-export   $IMG  $EXPORT_FILE

# --------------------------------------------------------------------------
# Import the net file system into a new smaller image with just one layer

echo "----------------------------------------------------------------------"
echo "Re-importing crosslinked file system..."
time squash-import   $IMG $EXPORT_FILE
